[
    [/NameError: name '(\w+)' is not defined/g, "没有定义过 $1"],
    [/TokenError: EOF in multi-line statement/g, "语法错误😢"],
    [/ParseError: bad input/g, "语法错误😢"],
    [/ParseError: bad token/g, "语法错误😢"],
    [/SyntaxError: bad input/g, "语法错误😢"],
    [/SyntaxError: bad token/g, "语法错误😢"],
    [/TypeError: unsupported operand type\(s\) for Add: '(\w+)' and '(\w+)'/g, "加法不能用来加 '$1' 和 '$2'"],
    [/TypeError: cannot concatenate '(\w+)' and '(\w+)' objects/g, "加法不能用来加 '$1' 和 '$2'"],
    [/AttributeError: '(\w+)' object has no attribute '(\w+)'/g, "'$1' 没有 '$2' 命令"],
    [/TypeError: 'list' object is not callable/g, "要使用列表的元素, 要使用\[\] 而不是\(\)"],
    [/TypeError: 'str' object is not callable/g, "小括号\(\)一定要紧跟在命令后面"],
    [/TypeError: 'int' object is not callable/g, "小括号\(\)一定要紧跟在命令后面"],
    [/TypeError: '(\w+)' object is not callable/g, "小括号\(\)一定要紧跟在命令后面, 但是前面是'$1'"],
    [/TypeError: '(\w+)' does not support indexing/g, "中括号\[\]一定要紧跟在列表,字符串,字典后面, 但是前面是'$1'"],
    [/ZeroDivisionError: integer division or modulo by zero/g, "除数不能为0"],
    [/ImportError: No module named (\w+)/g, "找不到叫 $1 的库, 不能导入"],
    [/TypeError: (\w+)\(\) takes exactly (\d+) positional argument\(s\) \((\d+) given\)/g, "$1\(\) 里要写 $2 个参数, 但你写了 $3 个"],
    [/TypeError: (\w+)\(\) takes between (\d+) and (\d+) positional argument\(s\) \((\d+) given\)/g, "$1\(\) 里可以写 $2 到 $3 个参数, 但你写了 $4 个"],
    [/NotImplementedError: (\w+) is not yet implemented/g, "不要调皮哦, 网页上还没有实现 $1"],
    [/ExternalError: todo; haven't implemented (.+)/g, "不要调皮哦, 网页上还没有实现 $1"],
    [/string/g, "string(字符串)"],
    [/number/g, "number(数字)"],
    [/'list'/g, "'list'\(列表\)"],
    [/'int'/g, "'int'\(整数\)"],
    [/'str'/g, "'str'\(字符串\)"],
    [/'dict'/g, "'dict'\(字典\)"],
    [/'float'/g, "'float'\(小数\)"],
    [/on line (\d+)/g, ", 在第 $1 行"]
]